// frontend/src/types/index.ts

export type CaseType = 'Civil Dispute' | 'Criminal Defense' | 'Family Law' | 'Intellectual Property' | 'Corporate Law' | 'Other';
export type CaseStatus = 'Open' | 'Closed' | 'Pending' | 'Archived';

export interface Case {
  id: number;
  caseNumber: string;
  title: string;
  description?: string;
  type: CaseType;
  status: CaseStatus;
  userId: number;
  createdAt: string;
  updatedAt: string;
}

export interface Document {
  id: number;
  caseId: number;
  fileName: string;
  storagePath: string;
  fileType: string;
  fileSize: number;
  createdAt: string;
  processingStatus: 'PENDING' | 'PROCESSED' | 'FAILED';
}

export interface Message {
  id?: number; // Optional as it's generated by the DB
  caseId?: number;
  sender: 'user' | 'bot';
  text: string;
  createdAt?: string;
}
